name: Update Prices Daily

on:
  schedule:
    - cron: '0 7 * * *' # каждый день в 07:00 UTC
  workflow_dispatch:

jobs:
  update-prices:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
      - name: Run price update script
        run: python update.py
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add prices.json
          git commit -m "Daily price update"
          git push
        continue-on-error: true
